import React, { useEffect, useState } from 'react';
import { Screen, RegisteredUser } from '../types';
import { isSupabaseConfigured, supabase } from '../lib/supabaseClient';
import { BookOpen, ExternalLink, LayoutDashboard, LogOut, MessageSquareQuote, Package, Settings, Users } from 'lucide-react';

type Area = 'products' | 'pages' | 'courses' | 'users' | 'testimonials' | 'settings';
type Product = { id: string; name: string; price: number; stock: number; description: string; featured: boolean };
type Props = { users: RegisteredUser[]; onLogout: () => void; onNavigate: (screen: Screen) => void; onDeleteUser: (id: string) => void; onUpdateUser: (user: RegisteredUser) => Promise<void> | void; onSyncDatabase: () => void; isSyncing: boolean };
const areas: [Area, string, React.ElementType][] = [['products', 'Productos', Package], ['pages', 'Páginas', LayoutDashboard], ['courses', 'Cursos', BookOpen], ['users', 'Usuarios', Users], ['testimonials', 'Testimonios', MessageSquareQuote], ['settings', 'Ajustes', Settings]];
const productSections = ['Productos', 'Subir producto', 'Categorías', 'Pedidos', 'Portada / Hero', 'Métricas'];
const Empty = ({ title, text }: { title: string; text: string }) => <div className="border border-dashed border-[#E8E3DA] bg-white px-6 py-16 text-center"><Package className="mx-auto mb-3 h-8 w-8 text-[#C9A24D]" /><h3 className="font-display text-xl">{title}</h3><p className="mt-2 text-sm text-[#667085]">{text}</p></div>;

export default function AdminDashboardProView({ users, onLogout, onNavigate, onDeleteUser, onUpdateUser, onSyncDatabase, isSyncing }: Props) {
  const [area, setArea] = useState<Area>('products');
  const [productSection, setProductSection] = useState('Productos');
  const [products, setProducts] = useState<Product[]>([]);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  useEffect(() => { if (isSupabaseConfigured) supabase.from('products').select('*').order('created_at', { ascending: false }).then(({ data, error }) => { if (error) setNotice(error.message); else setProducts((data || []) as Product[]); }); }, []);
  const saveProduct = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await supabase.from('products').insert({ name: data.get('name'), description: data.get('description'), price: Number(data.get('price')) || 0, stock: Number(data.get('stock')) || 0, image_url: data.get('image_url') || '', materials: data.get('materials') || '', featured: data.get('featured') === 'on' }); if (result.error) setNotice(result.error.message); else { setNotice('Producto guardado.'); event.currentTarget.reset(); const refreshed = await supabase.from('products').select('*').order('created_at', { ascending: false }); setProducts((refreshed.data || []) as Product[]); } };
  const removeProduct = async (id: string) => { if (!confirm('¿Eliminar este producto?')) return; const result = await supabase.from('products').delete().eq('id', id); if (result.error) setNotice(result.error.message); else { setProducts((items) => items.filter((item) => item.id !== id)); setNotice('Producto eliminado.'); } };
  const filtered = products.filter((product) => `${product.name} ${product.description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="min-h-screen bg-[#FAF9F6] text-[#151515]"><header className="bg-[#1B1B1B] px-4 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-[#E3C27D]">XLMX Barber</p><h1 className="font-display text-2xl">Panel administrativo</h1></div><div className="flex gap-2"><button onClick={() => onNavigate('home')} className="flex items-center gap-2 border border-white/20 px-3 py-2 text-sm"><ExternalLink className="h-4 w-4" /> Ver sitio</button><button onClick={() => { onLogout(); onNavigate('home'); }} className="flex items-center gap-2 bg-[#C9A24D] px-3 py-2 text-sm text-[#151515]"><LogOut className="h-4 w-4" /> Cerrar sesión</button></div></div></header><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-6 sm:px-8 lg:flex-row"><aside className="w-full shrink-0 lg:w-60"><nav className="grid grid-cols-2 gap-1 sm:grid-cols-3 lg:grid-cols-1">{areas.map(([id, label, Icon]) => <button key={id} onClick={() => setArea(id)} className={`flex items-center gap-3 px-3 py-3 text-left text-sm ${area === id ? 'bg-[#1B1B1B] text-white' : 'text-[#667085] hover:bg-white'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>{area === 'products' && <nav className="mt-3 space-y-1 border-l-2 border-[#E3C27D] pl-3">{productSections.map((section) => <button key={section} onClick={() => setProductSection(section)} className={`block w-full px-2 py-2 text-left text-xs ${productSection === section ? 'font-semibold' : 'text-[#667085]'}`}>{section}</button>)}</nav>}</aside><main className="min-w-0 flex-1"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#C9A24D]">Control del sitio</p><h2 className="font-display text-3xl">{areas.find(([id]) => id === area)?.[1]}</h2></div><button onClick={() => { onSyncDatabase(); }} className="border border-[#E8E3DA] bg-white px-3 py-2 text-sm text-[#667085]">{isSyncing ? 'Actualizando...' : 'Actualizar datos'}</button></div>{notice && <p className="mb-4 border border-[#E3C27D] bg-[#FFF9E9] p-3 text-sm">{notice}</p>}
{area === 'products' && productSection === 'metrics' && <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Productos', products.length], ['Stock bajo', products.filter((p) => p.stock <= 5).length], ['Destacados', products.filter((p) => p.featured).length], ['Pedidos', 0]].map(([label, value]) => <div key={String(label)} className="border border-[#E8E3DA] bg-white p-5"><p className="text-xs text-[#667085]">{label}</p><p className="mt-3 font-display text-2xl">{value}</p></div>)}</div>}
{area === 'products' && (productSection === 'Productos' || productSection === 'Subir producto') && <section><div className="mb-4 flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar productos" className="flex-1 border border-[#E8E3DA] bg-white px-3 py-2 text-sm" /></div><form onSubmit={saveProduct} className="mb-5 grid gap-3 border border-[#E3C27D] bg-white p-5 sm:grid-cols-2"><input name="name" required placeholder="Nombre" className="border p-2" /><input name="price" type="number" placeholder="Precio" className="border p-2" /><input name="stock" type="number" placeholder="Stock" className="border p-2" /><input name="image_url" placeholder="Imagen URL" className="border p-2" /><input name="materials" placeholder="Materiales" className="border p-2" /><textarea name="description" placeholder="Descripción" className="border p-2" /><label><input name="featured" type="checkbox" /> Producto destacado</label><button className="w-fit bg-[#C9A24D] px-4 py-2 text-sm">Guardar cambios</button></form>{filtered.length === 0 ? <Empty title="Sin productos" text="No hay datos reales cargados." /> : filtered.map((product) => <div key={product.id} className="mb-2 flex justify-between border border-[#E8E3DA] bg-white p-4"><span>{product.name} · ${product.price} · stock {product.stock}</span><button onClick={() => removeProduct(product.id)} className="text-[#F50078]">Eliminar</button></div>)}</section>}
{area === 'products' && ['categories', 'orders', 'hero'].includes(productSection.toLowerCase()) && <Empty title="Sin datos configurados" text="Esta subárea mostrará registros reales de Supabase." />}
{area === 'courses' && <Empty title="Sin cursos" text="Cursos, secciones, lecciones, videos y accesos se mostrarán desde Supabase." />}
{area === 'pages' && <Empty title="Sin páginas" text="Configura registros reales en site_pages para editarlos." />}
{area === 'users' && (users.length ? users.map((user) => <article key={user.id} className="mb-3 border border-[#E8E3DA] bg-white p-4"><p className="font-display text-xl">{user.fullname}</p><p className="text-sm text-[#667085]">ID: {user.id} · {user.email} · {user.age} años</p><button onClick={() => onUpdateUser(user)} className="mt-2 text-sm text-[#C9A24D]">Guardar cambios</button><button onClick={() => onDeleteUser(user.id)} className="ml-4 text-sm text-[#F50078]">Eliminar</button></article>) : <Empty title="Sin usuarios" text="Los usuarios reales aparecerán aquí al registrarse." />)}
{area === 'testimonials' && <Empty title="Sin testimonios" text="Las reseñas reales aparecerán aquí para moderación." />}{area === 'settings' && <Empty title="Ajustes protegidos" text="Roles, contraseñas, backups e integraciones requieren Supabase Auth, RLS y backend seguro." />}</main></div></div>;
}
